name: my_movie_list_v2
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Network
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ">=4.0.0 <5.0.0"
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1

  # Helper
  logger: ^2.0.2+1
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.5
  photo_view: ^0.14.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.6
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  easy_localization: ^3.0.3
  device_info_plus: ^9.1.0
  connectivity_plus: ^5.0.1
  package_info_plus: ^4.2.0
  internet_connection_checker_plus: ^2.1.0

  # UI
  shimmer: ^3.0.0
  animations: ^2.0.8
  animate_do: ^3.1.2
  lottie: ^2.7.0
  badges: ^3.1.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9

  # State Mangement
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ">=7.0.0 <8.0.0"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
